apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: bestbuy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: hycst/bestbuy-order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: AMQP_URL
              value: amqp://guest:guest@rabbitmq:5672
            - name: ORDER_DB_URI
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: ORDER_DB_URI
            - name: ORDER_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: ORDER_DB_NAME
            - name: ORDER_DB_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: ORDER_DB_COLLECTION_NAME
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: RABBITMQ_PORT
            - name: ORDER_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: ORDER_QUEUE_NAME
            - name: ORDER_QUEUE_URI
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: ORDER_QUEUE_URI
            - name: ORDER_QUEUE_HOST
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: ORDER_QUEUE_HOST
            - name: ORDER_QUEUE_PORT
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: ORDER_QUEUE_PORT
            - name: ORDER_QUEUE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bestbuy-secret
                  key: ORDER_QUEUE_USERNAME
            - name: ORDER_QUEUE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bestbuy-secret
                  key: ORDER_QUEUE_PASSWORD                
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bestbuy-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bestbuy-secret
                  key: RABBITMQ_PASSWORD             
            - name: ORDER_QUEUE_HOSTNAME
              valueFrom:
               configMapKeyRef:
                name: bestbuy-config
                key: ORDER_QUEUE_HOSTNAME      
                  
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: bestbuy
spec:
  selector:
    app: order-service
  ports:
    - port: 3000
      targetPort: 3000