apiVersion: v1
kind: Secret
metadata:
  name: bestbuy-secret
  namespace: bestbuy
type: Opaque
stringData:
  MONGO_USERNAME: admin
  MONGO_PASSWORD: password123
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: guest
  ORDER_QUEUE_USERNAME: guest
  ORDER_QUEUE_PASSWORD: guest